### ISSUE TITLE
ufo-launch: allow arbitrary graphs

### ISSUE THREAD

**Issue by matze** [ufo-kit/ufo-core#103]
Coming from [this](https://github.com/ufo-kit/tofu/issues/56) issue, my idea to specify arbitrary connections is similar to how the high-level API does it and which would avoid, weird "post specification" connection. The main problem right now is that we cannot connect multiple tasks to a single task. The most straightforward solution from my side would be to enhance the command line parser and use parentheses to group multiple inputs, e.g.

    $ ufo-launch ((A, B) ! C, D) ! E ! F

would specify a graph with `A->C_1`, `B->C_2`, `C->E_1`, `D->E_2`, `E->F`. Advantanges: shouldn't be too complicated to implement and is backwards-compatible. If @tfarago agrees, I'd try to fix this today.

**Comment by tfarago** [comment]
Yeah, why not. As long as it's there I am happy.

**Comment by matze** [comment]
There is one change to my initial proposal: one has to use brackets `[` and `]`, otherwise bash will complain. Other than that it works appropriately, i.e. something like that

    ufo-launch [read path=radios, read path=darks, read path=flats]! flat-field-correct ! write filename=foo.tif

does flat field correction.

**Comment by tfarago** [comment]
Looks great, this stuff will be priceless in the future, thanks!
