### ISSUE TITLE
ufo-launch doesn't accept quotes

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/ufo-core#105]
When I execute `ufo-launch read number=1 path=data/ ! calculate expression="v >= 255 ? 0 : v" ! write filename=./foo.tif` I get `Error: cannot parse pipeline specification`. Some time ago this used to work. Could you please fix it or is there some specific reason for this behavior?

**Comment by matze** [comment]
Actually it never worked in the sense that the quotes were required. The shell eats them anyway, so you could've also just left them out in the past. However, since we now have the more complex but also strict parser, you need to quote like this:

    ufo-launch read number=1 path=data/ ! calculate expression="'v >= 255 ? 0 : v'" ! write filename=./foo.tif

You *have* to use it like this.

**Comment by tfarago** [comment]
Thanks, works. Nice commit message by the way.
