### ISSUE TITLE
The manpages build process does not work on Unstable

### ISSUE THREAD

**Issue by picca** [ufo-kit/ufo-core#109]
Hello, I just tryed to build the man pages with the asciidoc available in Debian unstable

but I get this error.

    make -f docs/CMakeFiles/man.dir/build.make docs/CMakeFiles/man.dir/build
    make[3]: Entering directory '/<<PKGBUILDDIR>>/obj-i686-linux-gnu'
    [ 70%] Building manpage ufo-launch.1
    cd /<<PKGBUILDDIR>>/obj-i686-linux-gnu/docs && /usr/bin/a2x -D /<<PKGBUILDDIR>>/obj-i686-linux-gnu/docs/man/man1 -d manpage -f manpage /<<PKGBUILDDIR>>/docs/man/ufo-launch.1.txt
    a2x: WARNING: --destination-dir option is only applicable to HTML based outputs
    a2x: ERROR: "xmllint" --nonet --noout --valid "/<<PKGBUILDDIR>>/obj-i686-linux-gnu/docs/man/man1/ufo-launch.1.xml" returned non-zero exit status 127
    docs/CMakeFiles/man.dir/build.make:67: recipe for target 'docs/man/man1/ufo-launch.1' failed

and indded the man pages of a2x gives

       -D, --destination-dir=DESTINATION_DIR
           Output directory. Defaults to SOURCE_FILE directory. This option is only applicable to HTML based output formats (chunked, epub, htmlhelp, xhtml).

**Comment by picca** [comment]
I found this to get some inspiration

https://sources.debian.net/src/lizardfs/3.10.4%2Bdfsg-2/doc/CMakeLists.txt/?hl=68#L68

**Comment by matze** [comment]
The destination directory is not the problem (it's a warning I also get and which is [documented](https://github.com/asciidoc/asciidoc/issues/44)) but I will see if that recipe will fix that. Thanks Fred!

**Comment by matze** [comment]
I added the `-L` flag like lizardfs does . It presumably disables calling `xmllint` on the intermediate output. Could you check, if it builds for you now?

**Comment by picca** [comment]
Ok, It works with your patch
