### ISSUE TITLE
what about the python module and the tango devices

### ISSUE THREAD

**Issue by picca** [ufo-kit/ufo-core#113]
Hello.

I uploaded ufo-core but, then I realized that a tango device is available and also the ufo packages.

to my opinion, it would be nice toput the python modules into its own project and upload it into pypi. this would simplify the packaging a lot.

for the tango package I do not know if you would like to distribute it.
I should be the first tango devices distributed outside the tango package :)

cheers

Fred.

**Comment by matze** [comment]
Those things, I kind of consider as "contrib" material, that's why I didn't split it up further. However, even being part of `ufo-core` I can of course upload the support package to PyPI if this is still okay for you.

I wouldn't worry about  tango for though ... ;-)
