### ISSUE TITLE
Can I pass vectors to ufo-launch?

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/ufo-core#123]
something like `ufo-launch filter values=1,2,3`

**Comment by matze** [comment]
Not yet but I will work on it now, shouldn't take too long. Please be aware that command line lengths are limited (see `xargs --show-limits`), so avoid passing serialized images or the like :grin:

**Comment by tfarago** [comment]
Damn! That's exactly what I wanted it for :smile:
