### ISSUE TITLE
Memory corruption when UFO_DEVICES is set

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/ufo-core#129]
When I set `UFO_DEVICES=0,1,2,3,4,5,6` on the ufo2 machine and run any Ufo code I get something like
```bash
*** Error in `ufo-launch': malloc(): memory corruption: 0x0000000001773230 ***
```

**Comment by tfarago** [comment]
Actually, python-based graphs don't cause this error. However, when you do `export G_MESSAGES_DEBUG=all` the error occurs.

**Comment by matze** [comment]
Any kind of processing?

**Comment by tfarago** [comment]
I think yes, I just ran `ufo-launch read path=projections/ ! null`.

**Comment by matze** [comment]
Alright, I see that too.

**Comment by matze** [comment]
Ah yes, the wonders of manual memory management …
