### ISSUE TITLE
Compile kernels based on specific GPU info

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/ufo-core#135]
In [ufo-filters#140](https://github.com/ufo-kit/ufo-filters/pull/140) I would like to change the OpenCL kernel code based on a concrete GPU type. E.g. the `BURST` mode and some OpenCL compiler options depend on it. Should I compile the kernels in the first run of the `process` function then?

I think it would make sense to generalize this somehow, because things like local work size and so on are usually pretty GPU-specific. Especially when it comes to AMD/NVIDIA cards.

**Comment by matze** [comment]
1. For a long time now, kernels are compiled with the device name passed as an OpenCL compiler define that you can use in the kernel via `#ifdef` (see the [backproject kernel](https://github.com/ufo-kit/ufo-filters/blob/master/src/kernels/backproject.cl#L67-L83) which uses it to adapt the unroll number).
2. Yes, there would be nothing wrong to delay the kernel compilation until you know exactly the input size so either in `get_requisition` or `process`. `setup` is just convenience and guarantees it is executed exactly once at the beginning.

**Comment by tfarago** [comment]
1. I know, but I need it on the host side, is there a way to get it there? I need the GPU name for specifying compiler arguments, local work size and so on.

**Comment by matze** [comment]
Nope, no way as of now but I also don't see a problem extending `ufo_gpu_node_get_info()`.

**Comment by tfarago** [comment]
Will do.

**Comment by matze** [comment]
Before you rush implementing this, please move the `escape_device_name` to `ufo-priv.c/h` and make use of it in both the `UfoResources` and `UfoGpuNode` classes. Having the same name on both sides will avoid confusion.

**Comment by tfarago** [comment]
Yep, that sounds reasonable ;-) I am not in a hurry with this anyway, it's optimization for my PR so it will come last.

**Comment by matze** [comment]
At least that should be off your back now ;-)

**Comment by tfarago** [comment]
Many thanks! :+1:
