### ISSUE TITLE
Multi task input fails with crop filter

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/ufo-core#142]
When I do
```bash
ufo-launch read path=fc number=1 ! crop x=100 width=1916 ! flip direction=horizontal ! write filename=test/fc-%04i.tif
```
everything is fine, but when I do
```bash
ufo-launch [read path=fc number=1 ! crop x=100 width=1916, read path=fc number=1 ! crop x=100 width=1916 ! flip direction=horizontal] ! stitch shift=-1486 ! write filename=stitched/fc-%04i.tif
```
I get `(ufo-launch:15465): Ufo-WARNING **: target not found`
When the crop in the second reader which is flipped afterward is not present it works just fine. Could you take a look please?

**Comment by matze** [comment]
I cannot reproduce this behaviour. This works for me:

```bash
ufo-launch [dummy-data width=2048 height=2048 ! crop x=100 width=1916, dummy-data width=2048 height=2048 ! crop x=100 width=1916 ! flip direction=horizontal] ! stitch shift=-1486 ! write filename=stitched.tif
```

and is pretty much the same as what you do, except for using dummy data. Where do you see this?

**Comment by tfarago** [comment]
Aha, your command doesn't work for me either. It's on the new concert machine with fresh core and filters.

**Comment by matze** [comment]
Can you check the fix for your case?

**Comment by tfarago** [comment]
:+1:

**Comment by matze** [comment]
Nah, wait …
