### ISSUE TITLE
Raise minimum/maximum GLib and GObject version

### ISSUE THREAD

**Issue by matze** [ufo-kit/ufo-core#144]
This is more of a meta issue and covers more than just ufo-core but we have to start somewhere …

### Why?

First of all, the amount of deprecation warnings keep going up with `g_thread_*` and `g_static_mutex_*` being the worst offenders within our projects. If we raise the minimum version, we could drop those and use the replacements. Second, we are missing out on a lot of new features that have been developed since 2.30 (earliest release at the end of 2011 mind you!) and could make our lives easier. In particular things like `g_list_copy_deep`, the `g_test_*` function family, the `g_info` macro and the `g_auto*` macros could ease the development or harden the code.

### How?

I will check which versions we must support. If I find machines with clearly out-dated OSes I will kindly request to update the machine or consider using only older versions on that machine. They are not broken after all …

**Comment by tfarago** [comment]
👍

**Comment by matze** [comment]
Okay, I did a quick, non-exhaustive survey:

| Machine       | Distribution      | GLib version  |
| ------------- | ----------------- | ------------- |
| Tomas' laptop | Ubuntu 12.04      | 2.32.2        |
| compute1      | openSUSE 13.1     | 2.38.2        |
| compute2      | openSUSE 13.1     | 2.38.2        |
| compute3      | openSUSE 13.1     | 2.38.2        |
| ufo2          | openSUSE 13.1     | 2.38.2        |
| totoconcert   | Ubuntu 16.04      | 2.48.2        |
| camlin        | Ubuntu 16.04      | 2.48.2        |
|               | Ubuntu 14.04      | 2.40.0        |
|               | CentOS 7          | 2.50.3        |
|               | Debian Stretch    | 2.50.0        |
|               | Debian Buster     | 2.54.1        |

I think we can cross off Ubuntu 12.04 which was EOL'd in April 2017 and honestly we *should* cross off openSUSE 13.1 which was EOL'd February 2016. Ideally we could raise minimum versions to 2.48.2 but frankly speaking I don't think anyone is going to update all those machines still with 2.38.2 …

Anyway, as a first step I will raise to the safe 2.38.

**Comment by matze** [comment]
> Anyway, as a first step I will raise to the safe 2.38.

Yeah, I did that a while ago …
