### ISSUE TITLE
[doc] please get rid of sphinx-tabs

### ISSUE THREAD

**Issue by picca** [ufo-kit/ufo-core#145]
Hello Matthias.

I am sorry about that, but sphinx-tabs si not availabe in Debian. It would be great to package it but when We looked at the code of sphinx-tabs in order to prepare a package, it does not seems that easy to do... The python code is ok, BUT this extension embed a part of another Javascript framework semantic-ui (quite huge).

The problem is that the embeded code is minified so it is not the prefererd kind of sources for modifications expected by Debian . So for now it is not possible to have a clean documentation.

Is it possible to avoid this extension, even if I agree with you that it is really nice.

Once again sorry about that.

Fred

**Comment by matze** [comment]
Hmm, I will try to find some alternatives. In the worst case, I'll remove it again and just put the Python and C examples below each other.

**Comment by picca** [comment]
Hello,

I found a debian wiki about the semantic-ui packaging :((

https://wiki.debian.org/Javascript/Nodejs/Tasks/semantic-ui

Cheers, and once again sorry about that...

**Comment by picca** [comment]
Thanks alot Matthias

**Comment by matze** [comment]
You are welcome! Does this require a new release from my side for packaging in Debian?

**Comment by picca** [comment]
If it is lot's of work, we can deal with this. If it is not it would be nice :)

Cheers

**Comment by matze** [comment]
No problem. See https://github.com/ufo-kit/ufo-core/releases/tag/v0.15.2 and please notice that the 0.15.x release series is based on the 0.15 and not the master branch.

**Comment by picca** [comment]
We are using tags so this is not an issue for us.

Cheers
