### ISSUE TITLE
Graph does not expand to all GPUs

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/ufo-core#146]
I just tried on the new ankatoto-concert and
`ufo-launch --quiet dummy-data width=2016 height=3000 number=2016 ! fft ! filter ! ifft ! backproject ! null download=true` uses only one GPU. Same command on ankaimageufo2 runs on all cards (although far from saturation, but that's for another day). I output the debug and UFO says it's expanding for 4 cards on the ankatoto-concert, weird... Of course I am on fresh masters on both core and filters.

**Comment by matze** [comment]
Cannot test because the cards are saturated at the moment. Let me know, when you are done.

**Comment by tfarago** [comment]
Aha! That's why I got memory error some minutes ago :smile: You can try now and let me know when you are done please, I will continue my stuff on the machine.

**Comment by matze** [comment]
Alright, done. Since this is rather severe it means another bugfix release …
