### ISSUE TITLE
Simplify ufo_resources_get_kernel_* family

### ISSUE THREAD

**Issue by matze** [ufo-kit/ufo-core#150]
Currently, there are way too many ways to compile a kernel. We could simplify this by allowing options to be `NULL` and remove all the `_with_opts` functions.

**Comment by matze** [comment]
@tfarago what do you think about this? This will break virtually *all* filters (from the developer's point of view) but the way it is now is a bit redundant.

**Comment by tfarago** [comment]
I completely agree, one function would be great to have.

**Comment by matze** [comment]
I would have expected more resistance because you once wanted to change a public API and I advised against it ;-)

An alternative would be to add a new call `compile_kernel` or similar and deprecate the old API for a while and then remove it eventually.

**Comment by tfarago** [comment]
> I would have expected more resistance because you once wanted to change a public API and I advised against it ;-)

But this will affect only developers of the filters and they have to be able to deal with that. Especially if you refactor all the tasks within a PR :smile:

> An alternative would be to add a new call compile_kernel or similar and deprecate the old API for a while and then remove it eventually.

We are not at 1.0 yet, so we are on the sage side and I wouldn't clutter things too much.

**Comment by matze** [comment]
Alright, that was an exercise in using Vim macros :smile:
