### ISSUE TITLE
Segmentation fault (core dumped) when use numpy(fromarray)

### ISSUE THREAD

**Issue by huyuhuster** [ufo-kit/ufo-core#177]
Dear developer,
        When I use numpy(fromarray) like this:

```
In [1]: import ufo.numpy
In [2]: import numpy as np
In [3]: a = [ i*np.eye(100, dtype=np.float32) for i in range(1, 10) ]
In [4]: ufo.numpy.fromarray(a[0])
```

I got the error:
`Segmentation fault (core dumped)`

Do you have any suggestions on how I can check the bug?

I build the ufo in docker container.  Python version is Python 3.6.12.  OS is centos7.
And I build the ufo like this:

```
RUN cd /ufo-core && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr .. && make install
RUN cd /ufo-filters && mkdir build && cd build && cmake ..  -DCMAKE_INSTALL_PREFIX=/usr && make install
RUN cd /tofu && python setup.py install
RUN cd /ufo-core/python && python setup.py install
```

**Comment by tfarago** [comment]
Thank you for the observation. I see the same in my Python2 environment. The ufo-numpy for Python3 hasn't been fully tested yet, I will do so in the foreseeable future.

**Comment by huyuhuster** [comment]
Thanks for your reply. I found I can use the memory-in to read from a NumPy buffer.  I guess I also can use the memory-out to transfer the buffer to the NumPy buffer. But I didn't find the correct way. Could you please give me some example codes for this?

**Comment by tfarago** [comment]
Try this (boiler-plate skimmed):

```python
import numpy as np

data = np.empty(shape, dtype=np.float32)
ptr = self.data.__array_interface__['data'][0]
mem_out_task.props.pointer = ptr
mem_out_task.props.max_size = data.nbytes
```

and similar for memory-in. Hope that helps.
