### ISSUE TITLE
ufo unable to read files

### ISSUE THREAD

**Issue by NeutroTom** [ufo-kit/ufo-core#190]
I recently had to reinstall ufo-core ufo filters and tofu, and am now running into the problem that ufo is unable to read any files.  

Running this test directly on the home directory (where the slice is located, autocomplete finds it there):  
`ufo-launch read path='slice00322.tif' ! blur size=20 sigma=5 ! write filename=testout.tif`
results in:  
Error executing pipeline: read: `slice00322.tif' does not match any files

I get the same result if I instead use the full path or any other location.  

Please tell me what kind of further information you need.   
Best regards

**Comment by tfarago** [comment]
This is strange, I assume you have tried without the single quotes? What is your terminal, bash? I also need OS and glib version, thanks.

**Comment by matze** [comment]
If you built yourself make sure you have have `libtiff-dev` installed.

**Comment by tfarago** [comment]
Oh, yes, thanks @matze, that's most probably it. Just check what meson outputs (or cmake) and look for something like "tiff dependency found". Ubuntu 18.04 cannot be the problem, we still have some servers with that OS running it.

**Comment by tfarago** [comment]
There is a list of packages to install for Ubuntu 20.04 [here](https://ufo-core.readthedocs.io/en/latest/install/linux.html#ubuntu-debian-tested-on-ubuntu-20-04-3-lts).

**Comment by NeutroTom** [comment]
Looks like libtiff-dev was the main issue there, I reran the installation and now it is working. There were quite a few dependencies that did somehow not get installed correctly, so I had to build them manually. But I think the issue there was with our local filesystem and permissions, not on your side.

Thank you for the help!
