### ISSUE TITLE
'No supported channel order found for CL_FLOAT image type' Error Encountered with Latest Version of ufo-core/filters

### ISSUE THREAD

**Issue by SyrakuShaikh** [ufo-kit/ufo-core#194]
Hello everyone,

Our research group has been using the ufo-kit RPM package on OpenSUSE, version 0.15.1, for some data processing tasks. Recently, we noticed that the related RPM package on OpenSUSE has disappeared... As a result, we attempted to compile the latest version of ufo-core and ufo-filters from the source code. We are still using the same dataset as before, but we encountered the following error message with the current version.
```bash
(process:687): ocl-CRITICAL **: 09:13:07.237: Error </opt/UFO/ufo-filters/src/ufo-pad-task.c:76>: CL_INVALID_OPERATION

(process:687): ocl-CRITICAL **: 09:13:09.946: Error </opt/UFO/ufo-filters/src/ufo-pad-task.c:181>: CL_INVALID_SAMPLER

(process:687): ocl-CRITICAL **: 09:13:09.946: Error </opt/UFO/ufo-filters/src/ufo-pad-task.c:76>: CL_INVALID_OPERATION

(process:687): Ufo-ERROR **: 09:13:09.946: No supported channel order found for CL_FLOAT image type
Trace/breakpoint trap (core dumped)
```

![UFO-CL_FLOAT-gdb](https://github.com/ufo-kit/ufo-core/assets/9691144/a7b2e8d8-83fa-4af0-9105-d8b42d3509a4)

After searching the source codes and also the commits of this repo, we find that this may be related to #179 , but not so sure.

Do you have any suggestions or tips regarding this error? Thank you!

**Comment by tfarago** [comment]
Hi, sorry for the late reply, this totally slipped my attention.
What OpenCL backend do you have? Also, the RPM packages are very outdated, we recommend using docker which always fetches the newest version, look [here](https://ufo-core.readthedocs.io/en/latest/install/docker.html).

**Comment by SyrakuShaikh** [comment]
Hi, thank you for your response. It seems we may have resolved the issue. Initially, when I posted this problem, we were using the `libOpenCL.so` from the Conda (Python) environment. However, after extensive troubleshooting, we discovered that by switching to the `libOpenCL.so` from the Nvidia libraries, the bug vanished.

**Comment by SyrakuShaikh** [comment]
And thank you for the suggestion about Docker. I think I cand close this issue.
