### ISSUE TITLE
Call plugin on demand

### ISSUE THREAD

**Issue by kamer16** [ufo-kit/ufo-core#38]
A new plug-in interface that acts as a generator (reader) but only outputs data from time to time (when it's called by the scheduler for new data).  Otherwise, the previous data is cached and reused.
For instance we have a reader plug-in R, a pattern-generator plug-in P and an algorithm plug-in A.  For each image generated from R, I would like to process each pattern generated from P using algorithm A.
The plug-in P is reinitialized when it has generated all the patterns and a new image is generated from R. 
(My implementation idea is when the scheduler is informed that P has finished generating its data, the scheduler can ask the reader to output a new image and then set P to its initial state).
Here is how the plug-ins are linked.
R P
 \ /
 A

**Comment by matze** [comment]
This is now possible with a (generalized) generator which allows for repeated generation phases.
