### ISSUE TITLE
Scheduler hanging on complex graph

### ISSUE THREAD

**Issue by kamer16** [ufo-kit/ufo-core#50]
Trying the following test results in a hanging scheduler  Okay  it might seem strange but the thing is the `averager` does not get all the inputs (only 3) , and therefor  any plug-in after the `averager` never gets called.

It is true that the graph does not make sense because `cl2` gets `n` inputs for `input=1` and only `1` input for `input=0`, in my case I would like `input=0` to simply be duplicated as this is my workaround to issue #38 .

```python
from gi.repository import Ufo

source = """
kernel void foo(global float *in1, global float *in2, global float *out)
{
    int idx = get_global_id(1) * get_global_size(0) + get_global_id(0);
    out[idx] = in1[idx] * in2[idx];
}"""


pm = Ufo.PluginManager()

copy = Ufo.CopyTask()
g1 = pm.get_task('generate')
g2 = pm.get_task('generate')
cl = pm.get_task('opencl')
cl2 = pm.get_task('opencl')
averager = pm.get_task('averager')
writer = pm.get_task('writer')

g1.set_properties(width=512, height=512, number=3)
g2.set_properties(width=512, height=512, number=3)
cl.set_properties(source=source, kernel='foo')
cl2.set_properties(source=source, kernel='foo')

g = Ufo.TaskGraph()

g.connect_nodes(g2, copy)
g.connect_nodes_full(g1, cl, 0)
g.connect_nodes_full(copy, cl, 1)
g.connect_nodes(cl, averager)

g.connect_nodes_full(averager, cl2, 0)
g.connect_nodes_full(copy, cl2, 1)

g.connect_nodes(cl2, writer)


sched = Ufo.FixedScheduler()
sched.run(g)
```

**Comment by matze** [comment]
Besides buffering, redistributing the data is an alternative solution but also requires user intervention. Anyway, since this can be fixed, I will close this issue in the mean time.
