### ISSUE TITLE
Calling same plugin  multiple times

### ISSUE THREAD

**Issue by kamer16** [ufo-kit/ufo-core#56]
Some plugins like `fft` can be used multiple times in the same applications.
For instance:
```
A -> fft -> ... -> A' 
B -> fft -> ... -> B'
```
You might also want to do:
```
A' = fft(A);
B' = fft(B);
C' = A' * B'
```
To do any of these, multiple `fft` plug-ins need to be created like `fft_1, fft_2, ... -- fft_n`.
It would be nice to have a way to be able to reuse the same plug-in multiple times.

I don't know how easily this can be done without too much overhead.
A simple solution is to have a `dup()` function for each plug-in, which returns a copy of
the plugin allowing the following syntax:
```
graph.connect_nodes(reader1, fft) 
graph.connect_nodes(reader2, fft.dup()) 
graph.connect_nodes(fft.get(0), ifft)
graph.connect_nodes(fft.get(1), ifft)
graph.connect_nodes_full(ifft.get(0), fft_mult, 0)
graph.connect_nodes_full(ifft.get(1), fft_mult, 1)
```
The second idea, where the user can only create output_plugins, and the
`graph.connect_nodes()` is the only way to create input_plugins, that comes to mind is something like:
```
# Function Prototype, returns the new input
# input_plugin graph_connect_nodes(input_plugin, output_plugin);
input_task A', B', C', A, B, C;
output_task reader1 = reader_task_new();
output_task reader2 = reader_task_new();
output_task fft = fft_task_new();
output_task ifft = ifft_task_new();
output_task fft_mult = fft_mult_task_new();
output_task writer = writer_task_new();

A = graph.connect_nodes(NULL, reader1);
B = graph.connect_nodes(NULL, reader2);
A' = graph.connect_nodes(A, fft);
B' = graph.connect_nodes(B, fft);
C' = graph.connect_nodes_full(A', fft_mult, 0);
C' = graph.connect_nodes_full(B', fft_mult, 1);
C = graph.connect_nodes(C', ifft);
_ = graph.connect_nodes(C, writer);  # Ignore output
```
My last solution, which is more focused on stream manipulation, would be something like
```
# Function Prototype
# output_stream graph_connect_nodes(input_stream, output_stream, plugin_task);
graph.connect_nodes(NULL, A, reader);
graph.connect_nodes(NULL, B, reader);
graph.connect_nodes(A, A', fft);
graph.connect_nodes(B, B', fft);
graph.connect_nodes_full(A', C', fft_mult, 0);
graph.connect_nodes_full(B', C', fft_mult, 1);
graph.connect_nodes(C', C, ifft);
graph.connect_nodes(C, NULL, writer);
```

This might even make broadcasting more trivial.

**Comment by matze** [comment]
I will close this for now, to reduce the boiler plate we have higher level Python wrappers in place for a while now.
