### ISSUE TITLE
ufo_signal_emit crashes with older GLib and/or Python versions

### ISSUE THREAD

**Issue by matze** [ufo-kit/ufo-core#76]
This is very likely due to an uninitialized Python environment (i.e. if it is not even used).

/cc @tfarago

**Comment by tfarago** [comment]
Actually, it didn't solve the problem for me, still segfaults.

**Comment by matze** [comment]
I was getting segfaults with pure C programs, so that issue is only partially related to your problem.

**Comment by tfarago** [comment]
So what now?

**Comment by matze** [comment]
Another problem, another issue, I suppose.
