### ISSUE TITLE
ufo_signal_emit crashes with older Python versions

### ISSUE THREAD

**Issue by matze** [ufo-kit/ufo-core#77]
This issue is similar to #76 but affects Python programs. In this case, the Python process segfaults when trying to release the GIL after successfully emitting the signal.

**Comment by matze** [comment]
@tfarago: please check again.

**Comment by tfarago** [comment]
It works now, thanks. I hope it still works on new operating systems...

**Comment by matze** [comment]
It does on Ubuntu 14.04.
