### ISSUE TITLE
OpenCL device properties access

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/ufo-core#80]
It would be helpful to be able to get some OpenCL device properties from UFO so that we don't have to use it in combination with e.g. `pyopencl`. E.g. I would need the maximum amount of global memory.

**Comment by matze** [comment]
Although this is straightforward superficially, I will use the opportunity to remove some of the awkward relationships between `Resources` and `ArchGraph`. This *will* however change the way how GPU nodes are queried from. I'll open a PR soon.
