### ISSUE TITLE
Properties between tasks are not copied

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/ufo-core#82]
It seems that task copying doesn't work. I noticed this when reconstructing with Concert on a machine with more graphic cards, where the tasks are (if I understand correctly) copied and fit to those graphic cards. You can try this:
```python
import numpy as np
from concert.coroutines.base import inject
from concert.coroutines.sinks import Result
from concert.ext.ufo import Backproject


def main(n=1024):
    b = Backproject(n/2.)
    sino = np.empty((n, n), dtype=np.float32)
    result = Result()

    inject((sino,), b(result()))
    b.wait()

    assert result.result.shape == (n, n)


if __name__ == '__main__':
    main()
```
which will fail because the `crop` task has width and height are set to 256 by default. If you do `EXPORT_CUDA_VISIBLE_DEVICES=0` everything works fine.

**Comment by matze** [comment]
If that does not work nothing would have ever worked. Unfortunately, I cannot connect to my (or any machine at KIT) at the moment, it's hard for me to check this. But you could add 
```c
ufo_task_graph_save_to_json (task_graph, "foo.json", NULL)
```
at [this line](https://github.com/ufo-kit/ufo-core/blob/master/ufo/ufo-scheduler.c#L632) and check if your assumption is really the case.

**Comment by tfarago** [comment]
I added it and the properties are not set to what I want. *But* I think I solved it for now in [Concert](https://github.com/ufo-kit/concert/commit/713226ccc4dbcd1a5e01c627397a2880d9b899ae). The thing is I was setting properties *after* the scheduler starts and I guess that's not very healthy... Is that a feature or a bug actually? Am I supposed to be allowed to change properties on the fly? If not you can close this.

**Comment by matze** [comment]
It's a … necessity. I expand the graph for all devices only once and copy the properties then. I used to sync properties with `g_object_bind_property` but that caused other problems (I have to look through the logs to see why). So, no, you should not change properties during execution.
