### ISSUE TITLE
CL_R image is not supported by Intel OpenCL

### ISSUE THREAD

**Issue by tfarago** [ufo-kit/ufo-core#86]
However, `CL_INTENSITY` with `CL_FLOAT` should work. Are you @matze sure, that when you use `CL_R` there is some space left? I mean it hints is but whether the implementations really do it I don't know. We should check this and if there is no space saved use the `CL_INTENSITY`.

**Comment by matze** [comment]
> Are you @matze sure, that when you use CL_R there is some space left?

What exactly do you mean by that?

But in general we could of course change to `CL_INTENSITY` if that helps with Intel OpenCL and does not break on NVIDIA and AMD.

**Comment by tfarago** [comment]
What I meant was you would have just one channel, so 1/4 of the data as opposed to `CL_RGBA`. However, I just read that the `CL_INTENSITY` should be stored also only in one channel, so there is no memory occupation difference. Let's change it then.
