### ISSUE TITLE
Problem during the buildprocess when producing debian package

### ISSUE THREAD

**Issue by picca** [ufo-kit/ufo-core#97]
Hello, We are working on the ufo-core packaging.

during the build process with Debian, We got this error message.

```
[ 76%] Running gtkdoc-mkhtml
cd /<<PKGBUILDDIR>>/obj-i586-linux-gnu/docs/reference && /usr/bin/gtkdoc-mkhtml --path="/<<PKGBUILDDIR>>/obj-i586-linux-gnu/ufo/../docs/reference" Ufo /<<PKGBUILDDIR>>/obj-i586-linux-gnu/ufo/../docs/reference/Ufo-docs.xml
warning: failed to load external entity "/<<PKGBUILDDIR>>/obj-i586-linux-gnu/docs/reference/xml/ufo-arch-graph.xml"
/<<PKGBUILDDIR>>/obj-i586-linux-gnu/ufo/../docs/reference/Ufo-docs.xml:37: element include: XInclude error : could not load /<<PKGBUILDDIR>>/obj-i586-linux-gnu/docs/reference/xml/ufo-arch-graph.xml, and no fallback was found
ufo/CMakeFiles/reference.dir/build.make:64: recipe for target 'docs/html.stamp' failed
```

so what is going one :)

**Comment by matze** [comment]
Do you run this from a clean build dir? That particular file is not referenced [anymore](https://github.com/ufo-kit/ufo-core/blob/b7798d6f7ffdaae41c7eedc32d97210b2f688894/docs/Ufo-docs.xml#L37).

**Comment by picca** [comment]
If I remember correctly I took the lastest release 0.8.0 from github and then I tryed to build it using cmake. So it seems to me thaht this is a clean builddir :). Maybe I am wrong :)

**Comment by matze** [comment]
Ah, okay, you're not compiling from HEAD. 

I will release a new version and let you know when that happened. There were quite some bug fixes and minor enhancements already since last May. I'll keep you updated.

**Comment by picca** [comment]
Ok, Usually I am using only the tag for the packaging.
I agree that in our case this should be more tighten to the HEAD. Nevertheless thanks.

**Comment by matze** [comment]
Hey, I just uploaded 0.9 of both the core and the filters. If there's still a problem, just re-open this issue.
