### ISSUE TITLE
make test gives no usefull information on my system

### ISSUE THREAD

**Issue by picca** [ufo-kit/ufo-core#98]
Hello, when I run make test, I get this error message.

picca@ORD03037:~/Projets/ufo-core$ make test
Running tests...
Test project /home/picca/Projets/ufo-core
    Start 1: test-suite
1/1 Test #1: test-suite .......................***Exception: Other  0.30 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.36 sec

The following tests FAILED:
          1 - test-suite (OTHER_FAULT)
Errors while running CTest
Makefile:137: recipe for target 'test' failed
make: *** [test] Error 8

Indeed, I do not have openCL available on my system :), but it would be nice to have an informative information instead of ***Exception: Other  0.30 sec :)

**Comment by picca** [comment]
Once I installed a software implementation, I got 

    $ clinfo 
    Number of platforms:                             1
      Platform Profile:                              FULL_PROFILE
      Platform Version:                              OpenCL 1.1 MESA 10.3.2
      Platform Name:                                 Default
      Platform Vendor:                               Mesa
      Platform Extensions:                           cl_khr_icd


     Platform Name:                                 Default

    $ make test

    Running tests...
    Test project /home/picca/Projets/ufo-core
        Start 1: test-suite
    1/1 Test #1: test-suite .......................***Exception: Other  0.03 sec

    0% tests passed, 1 tests failed out of 1

    Total Test time (real) =   0.04 sec

    The following tests FAILED:
          1 - test-suite (OTHER_FAULT)
    Errors while running CTest
    Makefile:137: recipe for target 'test' failed

**Comment by matze** [comment]
Noted. But I really wonder when this crept in. However, the real tragedy is that I can hardly run OpenCL-based tests on Travis which might have found this way earlier. But anyway, I'll fix that.

**Comment by matze** [comment]
Could you check again with current HEAD?

**Comment by picca** [comment]
Hello with the 0.9.0 version I get this error.

Cheers

    Running tests...
    /usr/bin/ctest --force-new-ctest-process -j1
    Test project /home/picca/Debian/ufo-core/ufo-core/obj-i586-linux-gnu
    Start 1: test-suite
    1/1 Test #1: test-suite .......................***Exception: Other  0.03 sec
    /no-opencl/buffer/location: OK
    /no-opencl/buffer/convert/8/host: OK
    /no-opencl/buffer/convert/8/data: OK
    /no-opencl/buffer/convert/16/host: OK
    /no-opencl/buffer/convert/16/data: OK
    **
    Ufo:ERROR:/home/picca/Debian/ufo-core/ufo-core/tests/test-    buffer.c:139:test_insert_metadata:     assertion failed: (g_value_get_float (other) == 3.14f)
    /no-opencl/buffer/metadata/insert: 


    0% tests passed, 1 tests failed out of 1

    Total Test time (real) =   0.04 sec

    The following tests FAILED:
              1 - test-suite (OTHER_FAULT)
    Errors while running CTest
    Makefile:86: recipe for target 'test' failed
    make[1]: *** [test] Error 8
    make[1]: Leaving directory '/home/picca/Debian/ufo-core/ufo-core/obj-i586-linux-gnu'
    dh_auto_test: make -j1 test ARGS+=-j1 returned exit code 2

**Comment by matze** [comment]
That is weird and never happened to me. But anyway, I just pushed a change that compares the float differently.

**Comment by picca** [comment]
I am using this to compare two floats.

    /*
     * Takes an expected double and a seen double and assumes the test passes if
     * those two numbers are within delta of each other.
     */
    int
    is_double(double wanted, double seen, double epsilon, const char *format, ...)
    {
        va_list args;
        int success;

        va_start(args, format);
        fflush(stderr);
        if ((isnan(wanted) && isnan(seen))
            || (isinf(wanted) && isinf(wanted) == isinf(seen))
            || fabs(wanted - seen) <= epsilon) {
            success = 1;
            okv(1, format, args);
        } else {
            success = 0;
            diag("wanted: %g", wanted);
            diag("  seen: %g", seen);
            okv(0, format, args);
        }
        return success;
}

**Comment by matze** [comment]
That's problably the best way to do it for general purpose comparison. However, in the failed unit test this would just be overkill since I know exactly what value I put in.

**Comment by matze** [comment]
HEAD does not fail with Debian 8 AFAICT, please re-open if still an issue.
